#pragma once

#define EVENT_MENU_SELECTED_START "EVENT_MENU_SELECTED_START"
#define EVENT_MENU_SELECTED_SETTINGS "EVENT_MENU_SELECTED_SETTINGS"
#define EVENT_MENU_SELECTED_HELP "EVENT_MENU_SELECTED_HELP"
#define EVENT_MENU_SELECTED_ABOUT "EVENT_MENU_SELECTED_ABOUT"

#define EVENT_LOADING_COMPLETE "EVENT_LOADING_COMPLETE"


#define EVENT_UNIT_DAMAGED "EVENT_UNIT_DAMAGED"
#define EVENT_UNIT_SPELL "EVENT_UNIT_SPELL"
#define EVENT_UNIT_BUFF_ADDED "EVENT_UNIT_BUFF_ADDED"
#define EVENT_UNIT_DIE "EVENT_UNIT_DIE"
#define EVENT_UNIT_COLLISION "EVENT_UNIT_COLLISION"
#define EVENT_UNIT_BUFF_ENDED "EVENT_UNIT_BUFF_ENDED"

#define EVENT_CONTROL_TOUCH_PARAMS_TOUCH "EVENT_CONTROL_TOUCH_PARAMS_TOUCH"
#define EVENT_CONTROL_TOUCH_BEGAN "EVENT_CONTROL_TOUCH_BEGAN"
#define EVENT_CONTROL_TOUCH_MOVED "EVENT_CONTROL_TOUCH_MOVED"
#define EVENT_CONTROL_TOUCH_ENDED "EVENT_CONTROL_TOUCH_ENDED"

#define EVENT_GAME_STARTED "EVENT_GAME_STARTED"
#define EVENT_GAME_PAUSED "EVENT_GAME_PAUSED"
#define EVENT_GAME_RESUMED "EVENT_GAME_RESUMED"
#define EVENT_GAME_OVER "EVENT_GAME_OVER"
#define EVENT_GAME_LEVEL_CLEAR "EVENT_GAME_LEVEL_CLEAR"
#define EVENT_GAME_STATE_CHANGED "EVENT_GAME_STATE_CHANGED"
#define EVENT_GAME_STATE_CHANGE_PARAMS_STATE "EVENT_GAME_STATE_CHANGE_PARAMS_STATE"
#define EVENT_GAME_STATE_CHANGE_PARAMS_LAST_STATE "EVENT_GAME_STATE_CHANGE_PARAMS_LAST_STATE"
#define EVENT_GAME_STATE_CHANGE_PARAMS_PARAMS "EVENT_GAME_STATE_CHANGE_PARAMS_PARAMS"